server:
  port: ${port:8762}
spring:  application:    name: ramesh
eureka:  client:    service-url:      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:    prefer-ip-address: true